[
  {
    "advisory": {
      "id": "RUSTSEC-2024-0376",
      "package": "tonic",
      "title": "Remotely exploitable Denial of Service in Tonic",
      "description": "## Impact\n\nWhen using `tonic::transport::Server` there is a remote DoS attack that can cause the server to exit cleanly on accepting a tcp/tls stream. This can be triggered via causing the accept call to error out with errors there were not covered correctly causing the accept loop to exit. \n\nMore information can be found [here](https://github.com/hyperium/tonic/issues/1897)\n\n## Patches\n\nUpgrading to tonic `0.12.3` and above contains the fix. \n\n## Workarounds\n\nA custom accept loop is a possible workaround.",
      "date": "2024-10-01",
      "aliases": [
        "CVE-2024-47609",
        "GHSA-4jwc-w2hc-78qv"
      ],
      "related": [],
      "collection": "crates",
      "categories": [
        "denial-of-service"
      ],
      "keywords": [
        "dos"
      ],
      "cvss": null,
      "informational": null,
      "references": [],
      "source": null,
      "url": "https://github.com/hyperium/tonic/security/advisories/GHSA-4jwc-w2hc-78qv",
      "withdrawn": null,
      "license": "CC0-1.0"
    },
    "affected": null,
    "versions": {
      "patched": [
        ">=0.12.3"
      ],
      "unaffected": [
        "<0.12.2"
      ]
    }
  }
]